---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kally.io.kally.io
  resources:
  - mondepls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kally.io.kally.io
  resources:
  - mondepls/finalizers
  verbs:
  - update
- apiGroups:
  - kally.io.kally.io
  resources:
  - mondepls/status
  verbs:
  - get
  - patch
  - update
