//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Kaloyan Aleksiev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MonConfigs) DeepCopyInto(out *MonConfigs) {
	{
		in := &in
		*out = make(MonConfigs, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonConfigs.
func (in MonConfigs) DeepCopy() MonConfigs {
	if in == nil {
		return nil
	}
	out := new(MonConfigs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonDepl) DeepCopyInto(out *MonDepl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonDepl.
func (in *MonDepl) DeepCopy() *MonDepl {
	if in == nil {
		return nil
	}
	out := new(MonDepl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonDepl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonDeplList) DeepCopyInto(out *MonDeplList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonDepl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonDeplList.
func (in *MonDeplList) DeepCopy() *MonDeplList {
	if in == nil {
		return nil
	}
	out := new(MonDeplList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonDeplList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonDeplSpec) DeepCopyInto(out *MonDeplSpec) {
	*out = *in
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make(MonConfigs, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Underlying.DeepCopyInto(&out.Underlying)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonDeplSpec.
func (in *MonDeplSpec) DeepCopy() *MonDeplSpec {
	if in == nil {
		return nil
	}
	out := new(MonDeplSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonDeplStatus) DeepCopyInto(out *MonDeplStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonDeplStatus.
func (in *MonDeplStatus) DeepCopy() *MonDeplStatus {
	if in == nil {
		return nil
	}
	out := new(MonDeplStatus)
	in.DeepCopyInto(out)
	return out
}
